name: beta

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git Committer
        id: setup-git-committer
        uses: ./.github/actions/setup-git-committer
        with:
          miko-app-id: ${{ vars.MIKO_APP_ID }}
          miko-app-secret: ${{ secrets.MIKO_APP_SECRET }}

      - name: Install Miko
        run: bun i -g miko-ai

      - name: Sync beta branch
        env:
          GH_TOKEN: ${{ steps.setup-git-committer.outputs.token }}
          MIKO_API_KEY: ${{ secrets.MIKO_API_KEY }}
        run: bun script/beta.ts
